# Generated by Django 4.1.2 on 2022-10-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='lyric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicapp.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicapp.artiste'),
        ),
    ]
